//go:build !wireinject
// +build !wireinject

// Code generated by Wire. DO NOT EDIT.
// （此檔對應 wire.go 的注入器；結構與 Wire 產出一致，可用 `wire` 指令重新產生。）

package main

import (
	"palscheduler/internal/api"
	"palscheduler/internal/app"
	"palscheduler/internal/scheduler"
)

func InitializeApp() (*app.App, error) {
	cfg, err := provideConfig()
	if err != nil {
		return nil, err
	}
	serverController := provideServerController(cfg)
	sch := scheduler.New(cfg, serverController)
	apiServer := api.New(cfg, sch)
	application := app.New(sch, apiServer)
	return application, nil
}
